apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: microservicedesign.azurecr.io/notification
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_MAIL_HOST
              value: "mailhog.mailhog.svc.cluster.local"
            - name: SPRING_MAIL_PORT
              value: "1025"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq.default.svc.cluster.local"